name: Unit Test

on:
  push:
  workflow_dispatch:

jobs:
  unit-test:
    name: UnitTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore packages
        run: dotnet restore
        working-directory: src
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: src
      - name: Unit Test
        run: dotnet test --configuration Release --no-build
        working-directory: src
      